### ISSUE TITLE
Bot fails to start

### ISSUE THREAD

**Issue by IonutP** [AxelBjork/Rush-Royale-Bot#36]
Unable to start the bot even if no changes were made to the system. I get the following errors:

```
Exception in thread Thread-22678:
Traceback (most recent call last):
  File "C:\Users\Asus VivoBook S\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\Asus VivoBook S\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Asus VivoBook S\Desktop\RRB\Src\gui.py", line 108, in start_bot
    self.bot_instance.bot_stop = False
AttributeError: 'RR_bot' object has no attribute 'bot_instance'
```

**Comment by AxelBjork** [comment]
Hello, this looks like it's hitting a timeout on the startup.

Does Scrcpy open correctly?

**Comment by IonutP** [comment]
![image](https://user-images.githubusercontent.com/5071098/184344326-5522fa64-d8a0-4128-b031-d10cf672c869.png)
I'm not sure but here's a screenshot from console and UI opened.

**Comment by IonutP** [comment]
Not sure if it was just me but i did the following:
1. went to bluestack folder and checked hd-adb devices
2. started the bot from cmd not powershell

Seems to work now.
