### ISSUE TITLE
what does this mean?

### ISSUE THREAD

**Issue by nymser** [AxelBjork/Rush-Royale-Bot#71]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\12092\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\12092\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\12092\Downloads\Rush-Royale-Bot-main (1)\Rush-Royale-Bot-main\Src\gui.py", line 109, in start_bot
    self.bot_instance.bot_stop = False
AttributeError: 'NoneType' object has no attribute 'bot_stop'

**Comment by Kurouoe** [comment]
i have the same issue and idk what it is

**Comment by Newb420** [comment]
on what version or you using the fork? i have same issue on fork but not orginal

**Comment by nymser** [comment]
using fork the recent one

**Comment by Newb420** [comment]
Try this
Go to Scr > bot_handler.py (right click edit with ide) > (ctrl + F find 'Event') Delete the column
'config_selector.move_window(event)' > Ctrl + S (save)

**Comment by nymser** [comment]
still the same says scrp not installed  too

**Comment by Newb420** [comment]
> still the same says scrp not installed too

Take .scrpy folder from orginal bot and place it in the new bot folder
