### ISSUE TITLE
failed to connect to 127.0.0.1:xxxxx

### ISSUE THREAD

**Issue by silverjaxx** [AxelBjork/Rush-Royale-Bot#78]
Hi guys, i could always run the bot without issues but now it gives me this error(s):

```
C:\Users\Admin\Desktop\RR WTF>call .bot_env\Scripts\activate.bat
* daemon not running; starting now at tcp:5037
* daemon started successfully
Scanning 127.0.0.1 Ports 48000 - 65000
Started 5667 threads
Ports Open: [49665, 49668, 49785, 49664, 49666, 49669, 49786, 49667]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Admin\Desktop\RR WTF\Src\gui.py", line 102, in start_bot
    self.bot_instance = bot_handler.start_bot_class(self.logger)
  File "C:\Users\Admin\Desktop\RR WTF\Src\bot_handler.py", line 63, in start_bot_class
    bot = bot_core.Bot()
  File "C:\Users\Admin\Desktop\RR WTF\Src\bot_core.py", line 27, in __init__
    raise Exception("No device found!")
Exception: No device found!
disconnected 127.0.0.1:49664
failed to connect to 127.0.0.1:49664
disconnected 127.0.0.1:49665
failed to connect to 127.0.0.1:49665
disconnected 127.0.0.1:49666
failed to connect to 127.0.0.1:49666
disconnected 127.0.0.1:49667
failed to connect to 127.0.0.1:49667
disconnected 127.0.0.1:49668
failed to connect to 127.0.0.1:49668
disconnected 127.0.0.1:49785
failed to connect to 127.0.0.1:49785
disconnected 127.0.0.1:49786
failed to connect to 127.0.0.1:49786
disconnected 127.0.0.1:49669
failed to connect to 127.0.0.1:49669
```

I didnt change any settings, restarted the bot and now it throws all kinds of error.

Anyone can help me out would be awesome!

Thanks

**Comment by GhostyyyPlays** [comment]
is your ADB on bluestacks switched on?

**Comment by silverjaxx** [comment]
> is your ADB on bluestacks switched on?

Yes its on, the bot worked perfectly fine untill yesterday. I havent changed anything except restarting the bot (and my computer)

**Comment by GhostyyyPlays** [comment]
when you start the bot , is it in the main bluestacks screen or in the home screen of the game?

**Comment by silverjaxx** [comment]
> when you start the bot , is it in the main bluestacks screen or in the home screen of the game?

In the home screen of the game

**Comment by GhostyyyPlays** [comment]
just try it from the home screen of bluestacks itself and see what happens .  i'll see what i can find so long

**Comment by silverjaxx** [comment]
> just try it from the home screen of bluestacks itself and see what happens . i'll see what i can find so long

Same error from the home screen. I tried restarting everything (bot and pc), fresh install from the bot, disabled firewall. 
Thanks for helping me!

**Comment by Newb420** [comment]
> > just try it from the home screen of bluestacks itself and see what happens . i'll see what i can find so long
> 
> Same error from the home screen. I tried restarting everything (bot and pc), fresh install from the bot, disabled firewall. Thanks for helping me!

In scr folder edit port_scan.py and find socket.setdefaulttimeout(0.1)

change it to 1 or .05 or mess with it and see if that fixes issue did for me
