### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by fabiowa15** [AxelBjork/Rush-Royale-Bot#90]
Does not work!

Error

* daemon not running; starting now at tcp:5037
* daemon started successfully
Found ADB device! emulator-5554
Exception in thread Thread-1 (start_bot):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Fabio\Downloads\Rush-Royale-Bot-main\Src\gui.py", line 102, in start_bot
    self.bot_instance = bot_handler.start_bot_class(self.logger)
  File "C:\Users\Fabio\Downloads\Rush-Royale-Bot-main\Src\bot_handler.py", line 63, in start_bot_class
    bot = bot_core.Bot()
  File "C:\Users\Fabio\Downloads\Rush-Royale-Bot-main\Src\bot_core.py", line 39, in __init__
    self.client.start(threaded=True)
  File "C:\Users\Fabio\Downloads\Rush-Royale-Bot-main\.bot_env\lib\site-packages\scrcpy\core.py", line 189, in start
    self.__deploy_server()
  File "C:\Users\Fabio\Downloads\Rush-Royale-Bot-main\.bot_env\lib\site-packages\scrcpy\core.py", line 147, in __deploy_server
    self.device.sync.push(server_file_path, f"/data/local/tmp/{jar_name}")
  File "C:\Users\Fabio\Downloads\Rush-Royale-Bot-main\.bot_env\lib\site-packages\adbutils\_device.py", line 537, in push
    raise AdbError(status_msg)
adbutils.errors.AdbError: FAIL

**Comment by fabiowa15** [comment]
Solved problem: (Advanced) Android Debug Bridge: Enabled - Note the port number here.

**Comment by fabiowa15** [comment]
Solved problem: (Advanced) Android Debug Bridge: Enabled - Note the port number here.
