### ISSUE TITLE
cant launch bot

### ISSUE THREAD

**Issue by chriskenl** [AxelBjork/Rush-Royale-Bot#96]
C:\Users\Administrator\Desktop\Rush-Royale-Bot-main>call .bot_env\Scripts\activate.bat
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Rush-Royale-Bot-main\Src\gui.py", line 9, in <module>
    import bot_handler
  File "C:\Users\Administrator\Desktop\Rush-Royale-Bot-main\Src\bot_handler.py", line 10, in <module>
    import bot_core
  File "C:\Users\Administrator\Desktop\Rush-Royale-Bot-main\Src\bot_core.py", line 12, in <module>
    import bot_perception
  File "C:\Users\Administrator\Desktop\Rush-Royale-Bot-main\Src\bot_perception.py", line 5, in <module>
    from sklearn.linear_model import LogisticRegression
  File "C:\Users\Administrator\Desktop\Rush-Royale-Bot-main\.bot_env\lib\site-packages\sklearn\__init__.py", line 82, in
 <module>
    from .base import clone
  File "C:\Users\Administrator\Desktop\Rush-Royale-Bot-main\.bot_env\lib\site-packages\sklearn\base.py", line 17, in <mo
dule>
    from .utils import _IS_32BIT
  File "C:\Users\Administrator\Desktop\Rush-Royale-Bot-main\.bot_env\lib\site-packages\sklearn\utils\__init__.py", line
24, in <module>
    from .murmurhash import murmurhash3_32
  File "sklearn\utils\murmurhash.pyx", line 1, in init sklearn.utils.murmurhash
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObje
ct
PS C:\Users\Administrator\Desktop\Rush-Royale-Bot-main>

**Comment by jmatg1** [comment]
`pip install "numpy<2"`

**Comment by mleem97** [comment]
> `pip install "numpy<2"`

This indeed fixed it.

**Comment by ThienMrkid4** [comment]
I have the same problem, but after clicking launch it shuts down very quickly, I don't know where to type the command pip install "numpy<2". Please help me. It runs and shuts down without any place to type the next command to fix the error.

https://github.com/user-attachments/assets/cad44932-1c80-4e45-8b36-5f0c865b126e

**Comment by mleem97** [comment]
@ThienMrkid4 see #97 , you need to update requirements.txt

It should start.

**Comment by ThienMrkid4** [comment]
> [@ThienMrkid4](https://github.com/ThienMrkid4) see [#97](https://github.com/AxelBjork/Rush-Royale-Bot/pull/97) , you need to update requirements.txt
> 
> It should start.

very thanks you bro!
Can I add friends to your social network? I sent it

**Comment by mleem97** [comment]
What do you mean?

**Comment by ThienMrkid4** [comment]
I need your help to set up the farm, I wonder if you can add me on discord? My discord: gthien
